# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "firewire_ohci" "usbhid" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."crypt-files".device = "/dev/disk/by-uuid/eb0f7b3a-a450-4f8a-8c93-67db4e3dde05";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4e6eb6ec-f3fc-431f-b50d-7e2b00a42219";
      fsType = "ext4";
    };

  fileSystems."/home/bbush" =
    { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04";
      fsType = "btrfs";
      options = [ "subvol=bbush" "compress=zstd" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04";
      fsType = "btrfs";
      options = [ "subvol=data" "compress=zstd" ];
    };

  fileSystems."/scratch/gazelle.deploy.functionally.dev" =
    { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04";
      fsType = "btrfs";
      options = [ "subvol=gazelle.deploy.functionally.dev" "compress=zstd" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2a7dc867-f34f-49e5-9382-9101395b2c30"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
