# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "firewire_ohci" "usbhid" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4e6eb6ec-f3fc-431f-b50d-7e2b00a42219";
      fsType = "ext4";
    };

  fileSystems."/home/bbush" =
    { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04";
      fsType = "btrfs";
      options = [ "subvol=bbush" ];
    };

  fileSystems."/scratch/gdrive"                     = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=gdrive"                     ]; };
  fileSystems."/scratch/library.bwbush.io"          = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=library.bwbush.io"          ]; };
  fileSystems."/scratch/ed.bwbush.io"               = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=ed.bwbush.io"               ]; };
  fileSystems."/scratch/env.bwbush.io"              = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=env.bwbush.io"              ]; };
  fileSystems."/scratch/opt.bwbush.io"              = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=opt.bwbush.io"              ]; };
  fileSystems."/scratch/zotero.bwbush.io"           = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=zotero.bwbush.io"           ]; };
  fileSystems."/scratch/sangha.bwbush.io"           = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=sangha.bwbush.io"           ]; };
  fileSystems."/scratch/personal.bwbush.io"         = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=personal.bwbush.io"         ]; };
  fileSystems."//data"                              = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=data"                       ]; };
  fileSystems."/scratch/deploy.brianwbush.info"     = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=deploy.brianwbush.info"     ]; };
  fileSystems."/scratch/staging.bwbush.io"          = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=staging.bwbush.io"          ]; };
  fileSystems."/scratch/staging.brianwbush.info"    = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=staging.brianwbush.info"    ]; };
  fileSystems."/scratch/rkt-images.functionally.io" = { device = "/dev/disk/by-uuid/2bebc2f7-4df9-42f9-a563-e066b67b7f04"; fsType = "btrfs"; options = [ "subvol=rkt-images.functionally.io" ]; };

  boot.initrd.luks.devices."crypt-files".device = "/dev/disk/by-uuid/eb0f7b3a-a450-4f8a-8c93-67db4e3dde05";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/044bea2d-9fc3-4eb6-b086-f5467e3f8e34"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
